### ISSUE TITLE
Crash when detecting this .woff2 file

### ISSUE THREAD

**Issue by nifflin** [ross-spencer/sfclassic#1]
file url:

[https://github.com/smcduck/clean-executable-files/blob/master/test/testdata-not-executable/glyphicons-halflings-regular.woff2](url)

error output:

`goroutine 1 [running]:
github.com/richardlehane/siegfried/pkg/mimeinfo.applyScore(...)
        /Users/wongkashing/git/go/src/github.com/richardlehane/siegfried/pkg/mimeinfo/identifier.go:465
github.com/richardlehane/siegfried/pkg/mimeinfo.add(0xc0000f8080, 0x1, 0x1, 0xc001c2feb0, 0xf, 0xc00bb01170, 0x9, 0xc001c2d8a0, 0xa, 0x0, ...)
        /Users/wongkashing/git/go/src/github.com/richardlehane/siegfried/pkg/mimeinfo/identifier.go:522 +0xd51
github.com/richardlehane/siegfried/pkg/mimeinfo.(*Recorder).Record(0xc007e87b30, 0x3, 0x4453340, 0xc000bfe1e0, 0xc0000f8100)
        /Users/wongkashing/git/go/src/github.com/richardlehane/siegfried/pkg/mimeinfo/identifier.go:162 +0xb25
github.com/richardlehane/siegfried.(*Siegfried).IdentifyBuffer(0xc0077ca580, 0xc000a49900, 0x0, 0x0, 0x43d694f, 0xb, 0x0, 0x0, 0xc0000c0008, 0x0, ...)
        /Users/wongkashing/git/go/src/github.com/richardlehane/siegfried/siegfried.go:407 +0xca7
github.com/richardlehane/siegfried.(*Siegfried).Identify(0xc0077ca580, 0x444f960, 0xc000010010, 0x43d694f, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/wongkashing/git/go/src/github.com/richardlehane/siegfried/siegfried.go:450 +0x14e
github.com/ross-spencer/sfclassic.(*Siegfried).Identify(...)
        /Users/wongkashing/git/go/src/github.com/ross-spencer/sfclassic/sfclassic.go:32
`

**Comment by richardlehane** [comment]
this bug was fixed with the latest sf release (this is the [original issue](https://github.com/richardlehane/siegfried/issues/125)). But this repository hasn't been updated since that release - I can do this tonight.
Thanks for reporting Scrooge :)
